# Code Generated by Sidekick is for learning and experimentation purposes only.


module "vpc" {
  source = "./modules/vpc"

  availability_zone = var.availability_zone
}

module "security_group" {
  source = "./modules/security-group"

  vpc_id = module.vpc.vpc_id
  sg_name = "nginx-sg"
}

module "ec2_instance" {
  source = "./modules/ec2-instance"

  ami_id             = module.vpc.ami_id
  subnet_id          = module.vpc.subnet_id
  sg_id              = module.security_group.sg_id
  instance_type      = var.instance_type
  root_volume_size   = var.root_volume_size
  key_name           = var.key_name
  dynatrace_tenant   = var.dynatrace_tenant
  dynatrace_token    = var.dynatrace_token
}

