# Code Generated by Sidekick is for learning and experimentation purposes only.
resource "aws_ecs_task_definition" "dynatrace_test" {
  family                   = "${var.task_family}-dynatrace-test"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = aws_iam_role.ecs_task_execution_role.arn

  volume {
    name = "oneagent"
  }

  container_definitions = jsonencode([
    {
      name      = "install-oneagent"
      image     = "public.ecr.aws/docker/library/alpine:3.19"
      essential = false

      command = [
        "sh",
        "-c",
        "apk add --no-cache curl unzip file >/dev/null && mkdir -p /opt/dynatrace/oneagent && curl -fsSL -H \"Authorization: Api-Token $DT_PAAS_TOKEN\" \"$DT_ENV_URL/api/v1/deployment/installer/agent/unix/paas/latest?flavor=default&include=all\" -o /tmp/oneagent.zip && ls -l /tmp/oneagent.zip && unzip -o /tmp/oneagent.zip -d /opt/dynatrace/oneagent && test -f /opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so && echo 'OneAgent download and extract succeeded'"
      ]

      environment = [
        {
          name  = "DT_ENV_URL"
          value = var.dynatrace_environment_url
        }
      ]

      secrets = [
        {
          name      = "DT_PAAS_TOKEN"
          valueFrom = var.dynatrace_paas_token_secret_arn
        }
      ]

      mountPoints = [
        {
          sourceVolume  = "oneagent"
          containerPath = "/opt/dynatrace/oneagent"
          readOnly      = false
        }
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          awslogs-group         = "/ecs/nginx"
          awslogs-region        = "us-east-1"
          awslogs-stream-prefix = "dynatrace-test-install"
        }
      }
    },
    {
      name      = "verify-oneagent"
      image     = "public.ecr.aws/docker/library/alpine:3.19"
      essential = true

      dependsOn = [
        {
          containerName = "install-oneagent"
          condition     = "SUCCESS"
        }
      ]

      command = [
        "sh",
        "-c",
        "ls -R /opt/dynatrace/oneagent | head -100 && test -f /opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so && echo 'Verification passed: liboneagentproc.so exists'"
      ]

      mountPoints = [
        {
          sourceVolume  = "oneagent"
          containerPath = "/opt/dynatrace/oneagent"
          readOnly      = true
        }
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          awslogs-group         = "/ecs/nginx"
          awslogs-region        = "us-east-1"
          awslogs-stream-prefix = "dynatrace-test-verify"
        }
      }
    }
  ])
}
