# Code Generated by Sidekick is for learning and experimentation purposes only.
data "aws_region" "current" {}

locals {
  dynatrace_tenant = trimsuffix(var.dynatrace_tenant, "/")
}

resource "aws_cloudwatch_log_group" "dynatrace_test" {
  name              = "/ecs/dynatrace-test"
  retention_in_days = 7
}

resource "aws_iam_role" "ecs_task_execution_role" {
  name = "${var.ecs_cluster_name}-dynatrace-test-execution-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "ecs-tasks.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "ecs_task_execution_role_policy" {
  role       = aws_iam_role.ecs_task_execution_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

resource "aws_ecs_task_definition" "dynatrace_test" {
  family                   = "${var.task_family}-dynatrace-test"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = aws_iam_role.ecs_task_execution_role.arn

  volume {
    name = "oneagent"
  }

  container_definitions = jsonencode([
    {
      name      = "install-oneagent"
      image     = "public.ecr.aws/docker/library/alpine:3.19"
      essential = false

      command = [
        "sh",
        "-c",
        "apk add --no-cache curl unzip >/dev/null && mkdir -p /opt/dynatrace/oneagent && curl -fsSL -H \"Authorization: Api-Token $DT_API_TOKEN\" \"$DT_TENANT/api/v1/deployment/installer/agent/unix/paas/latest?flavor=default&include=all\" -o /tmp/oneagent.zip && ls -l /tmp/oneagent.zip && unzip -o /tmp/oneagent.zip -d /opt/dynatrace/oneagent && test -f /opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so && echo 'OneAgent download and extract succeeded'"
      ]

      environment = [
        {
          name  = "DT_TENANT"
          value = local.dynatrace_tenant
        },
        {
          name  = "DT_API_TOKEN"
          value = var.dynatrace_token
        }
      ]

      mountPoints = [
        {
          sourceVolume  = "oneagent"
          containerPath = "/opt/dynatrace/oneagent"
          readOnly      = false
        }
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          awslogs-group         = aws_cloudwatch_log_group.dynatrace_test.name
          awslogs-region        = data.aws_region.current.name
          awslogs-stream-prefix = "install"
        }
      }
    },
    {
      name      = "verify-oneagent"
      image     = "public.ecr.aws/docker/library/alpine:3.19"
      essential = true

      dependsOn = [
        {
          containerName = "install-oneagent"
          condition     = "SUCCESS"
        }
      ]

      command = [
        "sh",
        "-c",
        "ls -R /opt/dynatrace/oneagent | head -100 && test -f /opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so && echo 'Verification passed: liboneagentproc.so exists'"
      ]

      mountPoints = [
        {
          sourceVolume  = "oneagent"
          containerPath = "/opt/dynatrace/oneagent"
          readOnly      = true
        }
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          awslogs-group         = aws_cloudwatch_log_group.dynatrace_test.name
          awslogs-region        = data.aws_region.current.name
          awslogs-stream-prefix = "verify"
        }
      }
    }
  ])
}

output "dynatrace_test_task_definition_arn" {
  value = aws_ecs_task_definition.dynatrace_test.arn
}
