# Code Generated by Sidekick is for learning and experimentation purposes only.
data "aws_region" "current" {}

locals {
  dynatrace_tenant = trimsuffix(var.dynatrace_tenant, "/")
}

resource "aws_alb" "nginx_alb" {
  name               = "${var.ecs_cluster_name}-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [var.sg_id]
  subnets            = var.subnet_ids

  enable_deletion_protection = false

  tags = {
    Name = "nginx-alb"
  }
}

resource "aws_lb_target_group" "nginx_tg" {
  name_prefix = "ngtg-"
  port        = var.container_port
  protocol    = "HTTP"
  vpc_id      = var.vpc_id
  target_type = "ip"

  health_check {
    enabled             = true
    healthy_threshold   = 2
    interval            = 30
    matcher             = "200"
    path                = "/"
    port                = "traffic-port"
    protocol            = "HTTP"
    unhealthy_threshold = 2
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_lb_listener" "nginx_listener" {
  load_balancer_arn = aws_alb.nginx_alb.arn
  port              = 80
  protocol          = "HTTP"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.nginx_tg.arn
  }
}

resource "aws_ecs_cluster" "nginx_cluster" {
  name = var.ecs_cluster_name

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}

resource "aws_iam_role" "ecs_task_execution_role" {
  name = "${var.ecs_cluster_name}-execution-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "ecs-tasks.amazonaws.com"
        }
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "ecs_task_execution_role_policy" {
  role       = aws_iam_role.ecs_task_execution_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

resource "aws_iam_role" "ecs_task_role" {
  name = "${var.ecs_cluster_name}-task-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "ecs-tasks.amazonaws.com"
        }
      }
    ]
  })
}

resource "aws_cloudwatch_log_group" "ecs_logs" {
  name              = "/ecs/nginx"
  retention_in_days = 14
}

resource "aws_ecs_task_definition" "nginx_task" {
  family                   = var.task_family
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = aws_iam_role.ecs_task_execution_role.arn
  task_role_arn            = aws_iam_role.ecs_task_role.arn

  volume {
    name = "oneagent"
  }

  container_definitions = jsonencode([
    {
      name      = "install-oneagent"
      image     = "public.ecr.aws/docker/library/alpine:3.19"
      essential = false

      command = [
        "sh",
        "-c",
        "apk add --no-cache curl unzip >/dev/null && mkdir -p /opt/dynatrace/oneagent && curl -fsSL -H \"Authorization: Api-Token dt0c01.JQCQRMPU27SN3NP35HZXZPVB.HIE7JD2D5MLYRIWMQ6WAF4PMJPQXYDTXCEFCWNMAB6HGZLNJM4Y6FXLRBC5VMJJA\" \"https://${local.dynatrace_tenant}.live.dynatrace.com/api/v1/deployment/installer/agent/unix/paas/latest?flavor=musl&include=nginx\" -o /tmp/oneagent.zip && unzip -o /tmp/oneagent.zip -d /opt/dynatrace/oneagent && test -f /opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so && echo Dynatrace-OneAgent-ready"
      ]

      environment = [
        {
          name  = "DT_API_TOKEN"
          value = var.dynatrace_token
        }
      ]

      mountPoints = [
        {
          sourceVolume  = "oneagent"
          containerPath = "/opt/dynatrace/oneagent"
          readOnly      = false
        }
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          awslogs-group         = aws_cloudwatch_log_group.ecs_logs.name
          awslogs-region        = data.aws_region.current.name
          awslogs-stream-prefix = "install-oneagent"
        }
      }
    },
    {
      name      = "nginx"
      image     = var.nginx_image
      essential = true

      dependsOn = [
        {
          containerName = "install-oneagent"
          condition     = "SUCCESS"
        }
      ]

      portMappings = [
        {
          containerPort = var.container_port
          hostPort      = var.container_port
          protocol      = "tcp"
        }
      ]

      environment = [
        {
          name  = "LD_PRELOAD"
          value = "/opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so"
        },
        {
          name  = "DT_TENANT"
          value = local.dynatrace_tenant
        },
        {
          name  = "DT_CONNECTION_POINT"
          value = var.dynatrace_connection_point
        },
        {
          name  = "DT_LOGLEVELCON"
          value = "INFO"
        }
      ]

      mountPoints = [
        {
          sourceVolume  = "oneagent"
          containerPath = "/opt/dynatrace/oneagent"
          readOnly      = true
        }
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          awslogs-group         = aws_cloudwatch_log_group.ecs_logs.name
          awslogs-region        = data.aws_region.current.name
          awslogs-stream-prefix = "nginx"
        }
      }
    }
  ])
}

resource "aws_ecs_service" "nginx_service" {
  name            = "nginx-service"
  cluster         = aws_ecs_cluster.nginx_cluster.id
  task_definition = aws_ecs_task_definition.nginx_task.arn
  launch_type     = "FARGATE"
  desired_count   = var.ecs_desired_count

  network_configuration {
    subnets          = var.subnet_ids
    security_groups  = [var.sg_id]
    assign_public_ip = true
  }

  load_balancer {
    target_group_arn = aws_lb_target_group.nginx_tg.arn
    container_name   = "nginx"
    container_port   = var.container_port
  }

  depends_on = [aws_lb_listener.nginx_listener]
}
