# Code Generated by Sidekick is for learning and experimentation purposes only.
variable "vpc_id" {
  description = "VPC ID"
  type        = string
}

variable "subnet_ids" {
  description = "List of subnet IDs"
  type        = list(string)
}

variable "sg_id" {
  description = "Security group ID for ALB"
  type        = string
}
variable "dynatrace_tenant" {
  description = "https://abc123.live.dynatrace.com"
  type        = string
}

variable "dynatrace_connection_point" {
  description = "Dynatrace connection point or ActiveGate endpoint"
  type        = string
}

variable "dynatrace_token" {
  description = "Dynatrace installer token"
  type        = string
  sensitive   = true
}

variable "ecs_cluster_name" {
  description = "ECS cluster name"
  type        = string
}

variable "ecs_desired_count" {
  description = "Desired task count"
  type        = number
}

variable "nginx_image" {
  description = "Nginx image"
  type        = string
}

variable "task_family" {
  description = "Task family"
  type        = string
}

variable "container_port" {
  description = "Container port"
  type        = number
}
